fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=file, "-i"]
      - id: clang-tidy
        args: ["-p=build/default"]
      - id: cppcheck
        pass_filenames: false
        entry: cppcheck --project=build/default/compile_commands.json
        language: system
      - id: include-what-you-use
        entry: python3 tools/iwyu_hook.py -p build/default
        language: system
        files: '\.(c|cpp|h|hpp)$'
        require_serial: true
        pass_filenames: true