fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=file, "-i"]
      - id: clang-tidy
        args: ["-p=build/default"]
      - id: cppcheck
        pass_filenames: false
        args: ["--project=build/default/compile_commands.json", "--library=gtest,fmt,spdlog"]