name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      run: |
        pip install conan
        conan profile detect --force
    
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y ninja-build

    - name: Install dependencies
      working-directory: ${{ github.workspace }}
      run: conan install . --build missing --profile conan/profiles/debug --profile:build conan/profiles/debug --output-folder=build

    - name: Configure CMake
      working-directory: ${{ github.workspace }}
      run: cmake --preset debug

    - name: Build
      working-directory: ${{ github.workspace }}
      run: cmake --build --preset debug

    - name: Test
      working-directory: ${{ github.workspace }}
      run: ctest --preset debug